# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e55b8fd006529ff1ccc8d02f53b0356363864568c43fdda530fdfe501d2ab8b8032411f661668614d8b19db33a09bc3ca8d2cd5c2a9740be6ef215a236c7fe9a

test:
  secret_key_base: bee3aa06a9d7b4317b7be576f1aa9eb6de139c1434c65c394959aaa129cd48bee49a0a5bde8b9043c8dc9d83c3f734ce313c709511aa490d7e7345ee49612ed8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
